#spring.application.name=spwords

server:
  port: 8080

spring:
  application:
    name: spwords
  config:
    import:
      - classpath:config/application-secret.yml

  datasource:
    url: default
    username: default
    password: default

  jpa:
    hibernate:
      ddl-auto: validate  # create, create-drop, update, validate, none
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      base-url: default
      api-key: default
      chat:
        options:
          model: llama3-70b-8192
          temperature: 0.7

